/*
 * This file is generated by jOOQ.
 */
package ru.rich.matshop.db.model.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record13;
import org.jooq.Row13;
import org.jooq.impl.UpdatableRecordImpl;

import ru.rich.matshop.db.model.tables.AddressTable;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AddressRecord extends UpdatableRecordImpl<AddressRecord> implements Record13<Integer, Integer, String, String, String, String, String, String, String, String, String, String, Timestamp> {

    private static final long serialVersionUID = -421536328;

    /**
     * Setter for <code>matshop.address.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>matshop.address.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>matshop.address.person_id</code>.
     */
    public void setPersonId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>matshop.address.person_id</code>.
     */
    public Integer getPersonId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>matshop.address.region</code>.
     */
    public void setRegion(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>matshop.address.region</code>.
     */
    public String getRegion() {
        return (String) get(2);
    }

    /**
     * Setter for <code>matshop.address.town</code>.
     */
    public void setTown(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>matshop.address.town</code>.
     */
    public String getTown() {
        return (String) get(3);
    }

    /**
     * Setter for <code>matshop.address.street</code>.
     */
    public void setStreet(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>matshop.address.street</code>.
     */
    public String getStreet() {
        return (String) get(4);
    }

    /**
     * Setter for <code>matshop.address.house</code>.
     */
    public void setHouse(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>matshop.address.house</code>.
     */
    public String getHouse() {
        return (String) get(5);
    }

    /**
     * Setter for <code>matshop.address.housing</code>.
     */
    public void setHousing(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>matshop.address.housing</code>.
     */
    public String getHousing() {
        return (String) get(6);
    }

    /**
     * Setter for <code>matshop.address.construction</code>.
     */
    public void setConstruction(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>matshop.address.construction</code>.
     */
    public String getConstruction() {
        return (String) get(7);
    }

    /**
     * Setter for <code>matshop.address.apartment</code>.
     */
    public void setApartment(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>matshop.address.apartment</code>.
     */
    public String getApartment() {
        return (String) get(8);
    }

    /**
     * Setter for <code>matshop.address.entrance</code>.
     */
    public void setEntrance(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>matshop.address.entrance</code>.
     */
    public String getEntrance() {
        return (String) get(9);
    }

    /**
     * Setter for <code>matshop.address.intercom</code>.
     */
    public void setIntercom(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>matshop.address.intercom</code>.
     */
    public String getIntercom() {
        return (String) get(10);
    }

    /**
     * Setter for <code>matshop.address.address_comment</code>.
     */
    public void setAddressComment(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>matshop.address.address_comment</code>.
     */
    public String getAddressComment() {
        return (String) get(11);
    }

    /**
     * Setter for <code>matshop.address.edit_date</code>.
     */
    public void setEditDate(Timestamp value) {
        set(12, value);
    }

    /**
     * Getter for <code>matshop.address.edit_date</code>.
     */
    public Timestamp getEditDate() {
        return (Timestamp) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record13 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row13<Integer, Integer, String, String, String, String, String, String, String, String, String, String, Timestamp> fieldsRow() {
        return (Row13) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row13<Integer, Integer, String, String, String, String, String, String, String, String, String, String, Timestamp> valuesRow() {
        return (Row13) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return AddressTable.ADDRESS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return AddressTable.ADDRESS.PERSON_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return AddressTable.ADDRESS.REGION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return AddressTable.ADDRESS.TOWN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return AddressTable.ADDRESS.STREET;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return AddressTable.ADDRESS.HOUSE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return AddressTable.ADDRESS.HOUSING;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return AddressTable.ADDRESS.CONSTRUCTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return AddressTable.ADDRESS.APARTMENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return AddressTable.ADDRESS.ENTRANCE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return AddressTable.ADDRESS.INTERCOM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return AddressTable.ADDRESS.ADDRESS_COMMENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field13() {
        return AddressTable.ADDRESS.EDIT_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getPersonId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getRegion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getTown();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getStreet();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getHouse();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getHousing();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getConstruction();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getApartment();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getEntrance();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component11() {
        return getIntercom();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component12() {
        return getAddressComment();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component13() {
        return getEditDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getPersonId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getRegion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getTown();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getStreet();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getHouse();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getHousing();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getConstruction();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getApartment();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getEntrance();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getIntercom();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getAddressComment();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value13() {
        return getEditDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AddressRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AddressRecord value2(Integer value) {
        setPersonId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AddressRecord value3(String value) {
        setRegion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AddressRecord value4(String value) {
        setTown(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AddressRecord value5(String value) {
        setStreet(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AddressRecord value6(String value) {
        setHouse(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AddressRecord value7(String value) {
        setHousing(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AddressRecord value8(String value) {
        setConstruction(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AddressRecord value9(String value) {
        setApartment(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AddressRecord value10(String value) {
        setEntrance(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AddressRecord value11(String value) {
        setIntercom(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AddressRecord value12(String value) {
        setAddressComment(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AddressRecord value13(Timestamp value) {
        setEditDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AddressRecord values(Integer value1, Integer value2, String value3, String value4, String value5, String value6, String value7, String value8, String value9, String value10, String value11, String value12, Timestamp value13) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AddressRecord
     */
    public AddressRecord() {
        super(AddressTable.ADDRESS);
    }

    /**
     * Create a detached, initialised AddressRecord
     */
    public AddressRecord(Integer id, Integer personId, String region, String town, String street, String house, String housing, String construction, String apartment, String entrance, String intercom, String addressComment, Timestamp editDate) {
        super(AddressTable.ADDRESS);

        set(0, id);
        set(1, personId);
        set(2, region);
        set(3, town);
        set(4, street);
        set(5, house);
        set(6, housing);
        set(7, construction);
        set(8, apartment);
        set(9, entrance);
        set(10, intercom);
        set(11, addressComment);
        set(12, editDate);
    }
}
