/*
 * This file is generated by jOOQ.
 */
package ru.rich.matshop.db.model.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;
import ru.rich.matshop.db.model.tables.PCosmeticTable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PCosmeticRecord extends UpdatableRecordImpl<PCosmeticRecord> implements Record5<Long, Long, String, Long, String> {

    private static final long serialVersionUID = 1202748495;

    /**
     * Setter for <code>matshop.p_cosmetic.product_id</code>.
     */
    public void setProductId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>matshop.p_cosmetic.product_id</code>.
     */
    public Long getProductId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>matshop.p_cosmetic.price</code>.
     */
    public void setPrice(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>matshop.p_cosmetic.price</code>.
     */
    public Long getPrice() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>matshop.p_cosmetic.discount</code>.
     */
    public void setDiscount(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>matshop.p_cosmetic.discount</code>.
     */
    public String getDiscount() {
        return (String) get(2);
    }

    /**
     * Setter for <code>matshop.p_cosmetic.popularity</code>.
     */
    public void setPopularity(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>matshop.p_cosmetic.popularity</code>.
     */
    public Long getPopularity() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>matshop.p_cosmetic.brand</code>.
     */
    public void setBrand(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>matshop.p_cosmetic.brand</code>.
     */
    public String getBrand() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Long, Long, String, Long, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Long, Long, String, Long, String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return PCosmeticTable.P_COSMETIC.PRODUCT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return PCosmeticTable.P_COSMETIC.PRICE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return PCosmeticTable.P_COSMETIC.DISCOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field4() {
        return PCosmeticTable.P_COSMETIC.POPULARITY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return PCosmeticTable.P_COSMETIC.BRAND;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getProductId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getPrice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getDiscount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component4() {
        return getPopularity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getBrand();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getProductId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getPrice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getDiscount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value4() {
        return getPopularity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getBrand();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PCosmeticRecord value1(Long value) {
        setProductId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PCosmeticRecord value2(Long value) {
        setPrice(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PCosmeticRecord value3(String value) {
        setDiscount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PCosmeticRecord value4(Long value) {
        setPopularity(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PCosmeticRecord value5(String value) {
        setBrand(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PCosmeticRecord values(Long value1, Long value2, String value3, Long value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PCosmeticRecord
     */
    public PCosmeticRecord() {
        super(PCosmeticTable.P_COSMETIC);
    }

    /**
     * Create a detached, initialised PCosmeticRecord
     */
    public PCosmeticRecord(Long productId, Long price, String discount, Long popularity, String brand) {
        super(PCosmeticTable.P_COSMETIC);

        set(0, productId);
        set(1, price);
        set(2, discount);
        set(3, popularity);
        set(4, brand);
    }
}
