/*
 * This file is generated by jOOQ.
 */
package ru.rich.matshop.db.model.tables.records;


import java.util.Date;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record13;
import org.jooq.Row13;
import org.jooq.impl.UpdatableRecordImpl;

import ru.rich.matshop.db.model.tables.PersonAddressTable;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PersonAddressRecord extends UpdatableRecordImpl<PersonAddressRecord> implements Record13<Long, Long, String, String, String, String, String, String, String, String, String, String, Date> {

    private static final long serialVersionUID = -2099468584;

    /**
     * Setter for <code>matshop.person_address.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>matshop.person_address.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>matshop.person_address.person_id</code>.
     */
    public void setPersonId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>matshop.person_address.person_id</code>.
     */
    public Long getPersonId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>matshop.person_address.region</code>.
     */
    public void setRegion(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>matshop.person_address.region</code>.
     */
    public String getRegion() {
        return (String) get(2);
    }

    /**
     * Setter for <code>matshop.person_address.town</code>.
     */
    public void setTown(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>matshop.person_address.town</code>.
     */
    public String getTown() {
        return (String) get(3);
    }

    /**
     * Setter for <code>matshop.person_address.street</code>.
     */
    public void setStreet(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>matshop.person_address.street</code>.
     */
    public String getStreet() {
        return (String) get(4);
    }

    /**
     * Setter for <code>matshop.person_address.house</code>.
     */
    public void setHouse(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>matshop.person_address.house</code>.
     */
    public String getHouse() {
        return (String) get(5);
    }

    /**
     * Setter for <code>matshop.person_address.housing</code>.
     */
    public void setHousing(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>matshop.person_address.housing</code>.
     */
    public String getHousing() {
        return (String) get(6);
    }

    /**
     * Setter for <code>matshop.person_address.construction</code>.
     */
    public void setConstruction(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>matshop.person_address.construction</code>.
     */
    public String getConstruction() {
        return (String) get(7);
    }

    /**
     * Setter for <code>matshop.person_address.apartment</code>.
     */
    public void setApartment(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>matshop.person_address.apartment</code>.
     */
    public String getApartment() {
        return (String) get(8);
    }

    /**
     * Setter for <code>matshop.person_address.entrance</code>.
     */
    public void setEntrance(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>matshop.person_address.entrance</code>.
     */
    public String getEntrance() {
        return (String) get(9);
    }

    /**
     * Setter for <code>matshop.person_address.intercom</code>.
     */
    public void setIntercom(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>matshop.person_address.intercom</code>.
     */
    public String getIntercom() {
        return (String) get(10);
    }

    /**
     * Setter for <code>matshop.person_address.address_comment</code>.
     */
    public void setAddressComment(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>matshop.person_address.address_comment</code>.
     */
    public String getAddressComment() {
        return (String) get(11);
    }

    /**
     * Setter for <code>matshop.person_address.edit_date</code>.
     */
    public void setEditDate(Date value) {
        set(12, value);
    }

    /**
     * Getter for <code>matshop.person_address.edit_date</code>.
     */
    public Date getEditDate() {
        return (Date) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record13 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row13<Long, Long, String, String, String, String, String, String, String, String, String, String, Date> fieldsRow() {
        return (Row13) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row13<Long, Long, String, String, String, String, String, String, String, String, String, String, Date> valuesRow() {
        return (Row13) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return PersonAddressTable.PERSON_ADDRESS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return PersonAddressTable.PERSON_ADDRESS.PERSON_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return PersonAddressTable.PERSON_ADDRESS.REGION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return PersonAddressTable.PERSON_ADDRESS.TOWN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return PersonAddressTable.PERSON_ADDRESS.STREET;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return PersonAddressTable.PERSON_ADDRESS.HOUSE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return PersonAddressTable.PERSON_ADDRESS.HOUSING;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return PersonAddressTable.PERSON_ADDRESS.CONSTRUCTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return PersonAddressTable.PERSON_ADDRESS.APARTMENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return PersonAddressTable.PERSON_ADDRESS.ENTRANCE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return PersonAddressTable.PERSON_ADDRESS.INTERCOM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return PersonAddressTable.PERSON_ADDRESS.ADDRESS_COMMENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field13() {
        return PersonAddressTable.PERSON_ADDRESS.EDIT_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getPersonId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getRegion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getTown();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getStreet();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getHouse();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getHousing();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getConstruction();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getApartment();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getEntrance();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component11() {
        return getIntercom();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component12() {
        return getAddressComment();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date component13() {
        return getEditDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getPersonId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getRegion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getTown();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getStreet();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getHouse();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getHousing();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getConstruction();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getApartment();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getEntrance();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getIntercom();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getAddressComment();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value13() {
        return getEditDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PersonAddressRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PersonAddressRecord value2(Long value) {
        setPersonId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PersonAddressRecord value3(String value) {
        setRegion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PersonAddressRecord value4(String value) {
        setTown(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PersonAddressRecord value5(String value) {
        setStreet(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PersonAddressRecord value6(String value) {
        setHouse(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PersonAddressRecord value7(String value) {
        setHousing(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PersonAddressRecord value8(String value) {
        setConstruction(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PersonAddressRecord value9(String value) {
        setApartment(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PersonAddressRecord value10(String value) {
        setEntrance(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PersonAddressRecord value11(String value) {
        setIntercom(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PersonAddressRecord value12(String value) {
        setAddressComment(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PersonAddressRecord value13(Date value) {
        setEditDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PersonAddressRecord values(Long value1, Long value2, String value3, String value4, String value5, String value6, String value7, String value8, String value9, String value10, String value11, String value12, Date value13) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PersonAddressRecord
     */
    public PersonAddressRecord() {
        super(PersonAddressTable.PERSON_ADDRESS);
    }

    /**
     * Create a detached, initialised PersonAddressRecord
     */
    public PersonAddressRecord(Long id, Long personId, String region, String town, String street, String house, String housing, String construction, String apartment, String entrance, String intercom, String addressComment, Date editDate) {
        super(PersonAddressTable.PERSON_ADDRESS);

        set(0, id);
        set(1, personId);
        set(2, region);
        set(3, town);
        set(4, street);
        set(5, house);
        set(6, housing);
        set(7, construction);
        set(8, apartment);
        set(9, entrance);
        set(10, intercom);
        set(11, addressComment);
        set(12, editDate);
    }
}
