/*
 * This file is generated by jOOQ.
 */
package ru.rich.matshop.db.model.tables.records;


import java.util.Date;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;

import ru.rich.matshop.db.model.tables.ProductTable;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProductRecord extends UpdatableRecordImpl<ProductRecord> implements Record9<Long, Integer, String, Date, String, String, Long, String, String> {

    private static final long serialVersionUID = -1496279019;

    /**
     * Setter for <code>matshop.product.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>matshop.product.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>matshop.product.shop_id</code>.
     */
    public void setShopId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>matshop.product.shop_id</code>.
     */
    public Integer getShopId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>matshop.product.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>matshop.product.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>matshop.product.edit_date</code>.
     */
    public void setEditDate(Date value) {
        set(3, value);
    }

    /**
     * Getter for <code>matshop.product.edit_date</code>.
     */
    public Date getEditDate() {
        return (Date) get(3);
    }

    /**
     * Setter for <code>matshop.product.state</code>.
     */
    public void setState(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>matshop.product.state</code>.
     */
    public String getState() {
        return (String) get(4);
    }

    /**
     * Setter for <code>matshop.product.data</code>.
     */
    public void setData(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>matshop.product.data</code>.
     */
    public String getData() {
        return (String) get(5);
    }

    /**
     * Setter for <code>matshop.product.base_price</code>.
     */
    public void setBasePrice(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>matshop.product.base_price</code>.
     */
    public Long getBasePrice() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>matshop.product.pricing</code>.
     */
    public void setPricing(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>matshop.product.pricing</code>.
     */
    public String getPricing() {
        return (String) get(7);
    }

    /**
     * Setter for <code>matshop.product.format_version</code>.
     */
    public void setFormatVersion(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>matshop.product.format_version</code>.
     */
    public String getFormatVersion() {
        return (String) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Long, Integer, String, Date, String, String, Long, String, String> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Long, Integer, String, Date, String, String, Long, String, String> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return ProductTable.PRODUCT.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return ProductTable.PRODUCT.SHOP_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return ProductTable.PRODUCT.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field4() {
        return ProductTable.PRODUCT.EDIT_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return ProductTable.PRODUCT.STATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return ProductTable.PRODUCT.DATA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field7() {
        return ProductTable.PRODUCT.BASE_PRICE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return ProductTable.PRODUCT.PRICING;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return ProductTable.PRODUCT.FORMAT_VERSION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getShopId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date component4() {
        return getEditDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getState();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getData();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component7() {
        return getBasePrice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getPricing();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getFormatVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getShopId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value4() {
        return getEditDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getState();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getData();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value7() {
        return getBasePrice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getPricing();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getFormatVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductRecord value2(Integer value) {
        setShopId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductRecord value3(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductRecord value4(Date value) {
        setEditDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductRecord value5(String value) {
        setState(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductRecord value6(String value) {
        setData(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductRecord value7(Long value) {
        setBasePrice(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductRecord value8(String value) {
        setPricing(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductRecord value9(String value) {
        setFormatVersion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductRecord values(Long value1, Integer value2, String value3, Date value4, String value5, String value6, Long value7, String value8, String value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProductRecord
     */
    public ProductRecord() {
        super(ProductTable.PRODUCT);
    }

    /**
     * Create a detached, initialised ProductRecord
     */
    public ProductRecord(Long id, Integer shopId, String name, Date editDate, String state, String data, Long basePrice, String pricing, String formatVersion) {
        super(ProductTable.PRODUCT);

        set(0, id);
        set(1, shopId);
        set(2, name);
        set(3, editDate);
        set(4, state);
        set(5, data);
        set(6, basePrice);
        set(7, pricing);
        set(8, formatVersion);
    }
}
