/*
 * This file is generated by jOOQ.
 */
package ru.rich.matshop.db.model.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;

import ru.rich.matshop.db.model.tables.ProductCosmeticTable;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProductCosmeticRecord extends UpdatableRecordImpl<ProductCosmeticRecord> implements Record5<Integer, String, Long, Integer, Long> {

    private static final long serialVersionUID = 1123281318;

    /**
     * Setter for <code>matshop.product_cosmetic.product_id</code>.
     */
    public void setProductId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>matshop.product_cosmetic.product_id</code>.
     */
    public Integer getProductId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>matshop.product_cosmetic.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>matshop.product_cosmetic.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>matshop.product_cosmetic.price</code>.
     */
    public void setPrice(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>matshop.product_cosmetic.price</code>.
     */
    public Long getPrice() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>matshop.product_cosmetic.category</code>.
     */
    public void setCategory(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>matshop.product_cosmetic.category</code>.
     */
    public Integer getCategory() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>matshop.product_cosmetic.popularity</code>.
     */
    public void setPopularity(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>matshop.product_cosmetic.popularity</code>.
     */
    public Long getPopularity() {
        return (Long) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, String, Long, Integer, Long> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, String, Long, Integer, Long> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return ProductCosmeticTable.PRODUCT_COSMETIC.PRODUCT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return ProductCosmeticTable.PRODUCT_COSMETIC.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return ProductCosmeticTable.PRODUCT_COSMETIC.PRICE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return ProductCosmeticTable.PRODUCT_COSMETIC.CATEGORY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field5() {
        return ProductCosmeticTable.PRODUCT_COSMETIC.POPULARITY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getProductId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component3() {
        return getPrice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getCategory();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component5() {
        return getPopularity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getProductId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getPrice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getCategory();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value5() {
        return getPopularity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductCosmeticRecord value1(Integer value) {
        setProductId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductCosmeticRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductCosmeticRecord value3(Long value) {
        setPrice(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductCosmeticRecord value4(Integer value) {
        setCategory(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductCosmeticRecord value5(Long value) {
        setPopularity(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductCosmeticRecord values(Integer value1, String value2, Long value3, Integer value4, Long value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProductCosmeticRecord
     */
    public ProductCosmeticRecord() {
        super(ProductCosmeticTable.PRODUCT_COSMETIC);
    }

    /**
     * Create a detached, initialised ProductCosmeticRecord
     */
    public ProductCosmeticRecord(Integer productId, String name, Long price, Integer category, Long popularity) {
        super(ProductCosmeticTable.PRODUCT_COSMETIC);

        set(0, productId);
        set(1, name);
        set(2, price);
        set(3, category);
        set(4, popularity);
    }
}
