/*
 * This file is generated by jOOQ.
 */
package ru.rich.matshop.db.model.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;

import ru.rich.matshop.db.model.tables.ShopOrderHistory;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ShopOrderHistoryRecord extends UpdatableRecordImpl<ShopOrderHistoryRecord> implements Record9<Integer, Integer, String, String, Integer, String, String, Integer, Timestamp> {

    private static final long serialVersionUID = -1214587017;

    /**
     * Setter for <code>matshop.shop_order_history.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>matshop.shop_order_history.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>matshop.shop_order_history.shop_order_id</code>.
     */
    public void setShopOrderId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>matshop.shop_order_history.shop_order_id</code>.
     */
    public Integer getShopOrderId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>matshop.shop_order_history.old_state</code>.
     */
    public void setOldState(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>matshop.shop_order_history.old_state</code>.
     */
    public String getOldState() {
        return (String) get(2);
    }

    /**
     * Setter for <code>matshop.shop_order_history.old_service_comment</code>.
     */
    public void setOldServiceComment(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>matshop.shop_order_history.old_service_comment</code>.
     */
    public String getOldServiceComment() {
        return (String) get(3);
    }

    /**
     * Setter for <code>matshop.shop_order_history.old_assigned_person_id</code>.
     */
    public void setOldAssignedPersonId(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>matshop.shop_order_history.old_assigned_person_id</code>.
     */
    public Integer getOldAssignedPersonId() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>matshop.shop_order_history.new_state</code>.
     */
    public void setNewState(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>matshop.shop_order_history.new_state</code>.
     */
    public String getNewState() {
        return (String) get(5);
    }

    /**
     * Setter for <code>matshop.shop_order_history.new_service_comment</code>.
     */
    public void setNewServiceComment(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>matshop.shop_order_history.new_service_comment</code>.
     */
    public String getNewServiceComment() {
        return (String) get(6);
    }

    /**
     * Setter for <code>matshop.shop_order_history.new_assigned_person_id</code>.
     */
    public void setNewAssignedPersonId(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>matshop.shop_order_history.new_assigned_person_id</code>.
     */
    public Integer getNewAssignedPersonId() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>matshop.shop_order_history.event_date</code>.
     */
    public void setEventDate(Timestamp value) {
        set(8, value);
    }

    /**
     * Getter for <code>matshop.shop_order_history.event_date</code>.
     */
    public Timestamp getEventDate() {
        return (Timestamp) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, Integer, String, String, Integer, String, String, Integer, Timestamp> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, Integer, String, String, Integer, String, String, Integer, Timestamp> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return ShopOrderHistory.SHOP_ORDER_HISTORY.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return ShopOrderHistory.SHOP_ORDER_HISTORY.SHOP_ORDER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return ShopOrderHistory.SHOP_ORDER_HISTORY.OLD_STATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return ShopOrderHistory.SHOP_ORDER_HISTORY.OLD_SERVICE_COMMENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return ShopOrderHistory.SHOP_ORDER_HISTORY.OLD_ASSIGNED_PERSON_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return ShopOrderHistory.SHOP_ORDER_HISTORY.NEW_STATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return ShopOrderHistory.SHOP_ORDER_HISTORY.NEW_SERVICE_COMMENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return ShopOrderHistory.SHOP_ORDER_HISTORY.NEW_ASSIGNED_PERSON_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field9() {
        return ShopOrderHistory.SHOP_ORDER_HISTORY.EVENT_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getShopOrderId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getOldState();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getOldServiceComment();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getOldAssignedPersonId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getNewState();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getNewServiceComment();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component8() {
        return getNewAssignedPersonId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component9() {
        return getEventDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getShopOrderId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getOldState();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getOldServiceComment();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getOldAssignedPersonId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getNewState();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getNewServiceComment();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getNewAssignedPersonId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value9() {
        return getEventDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ShopOrderHistoryRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ShopOrderHistoryRecord value2(Integer value) {
        setShopOrderId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ShopOrderHistoryRecord value3(String value) {
        setOldState(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ShopOrderHistoryRecord value4(String value) {
        setOldServiceComment(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ShopOrderHistoryRecord value5(Integer value) {
        setOldAssignedPersonId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ShopOrderHistoryRecord value6(String value) {
        setNewState(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ShopOrderHistoryRecord value7(String value) {
        setNewServiceComment(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ShopOrderHistoryRecord value8(Integer value) {
        setNewAssignedPersonId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ShopOrderHistoryRecord value9(Timestamp value) {
        setEventDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ShopOrderHistoryRecord values(Integer value1, Integer value2, String value3, String value4, Integer value5, String value6, String value7, Integer value8, Timestamp value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ShopOrderHistoryRecord
     */
    public ShopOrderHistoryRecord() {
        super(ShopOrderHistory.SHOP_ORDER_HISTORY);
    }

    /**
     * Create a detached, initialised ShopOrderHistoryRecord
     */
    public ShopOrderHistoryRecord(Integer id, Integer shopOrderId, String oldState, String oldServiceComment, Integer oldAssignedPersonId, String newState, String newServiceComment, Integer newAssignedPersonId, Timestamp eventDate) {
        super(ShopOrderHistory.SHOP_ORDER_HISTORY);

        set(0, id);
        set(1, shopOrderId);
        set(2, oldState);
        set(3, oldServiceComment);
        set(4, oldAssignedPersonId);
        set(5, newState);
        set(6, newServiceComment);
        set(7, newAssignedPersonId);
        set(8, eventDate);
    }
}
