/*
 * This file is generated by jOOQ.
 */
package ru.rich.matshop.db.model.tables.records;


import java.util.Date;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;

import ru.rich.matshop.db.model.tables.ShopOrderHistoryTable;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ShopOrderHistoryRecord extends UpdatableRecordImpl<ShopOrderHistoryRecord> implements Record9<Long, Long, String, String, Long, String, String, Long, Date> {

    private static final long serialVersionUID = -1440640493;

    /**
     * Setter for <code>matshop.shop_order_history.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>matshop.shop_order_history.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>matshop.shop_order_history.shop_order_id</code>.
     */
    public void setShopOrderId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>matshop.shop_order_history.shop_order_id</code>.
     */
    public Long getShopOrderId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>matshop.shop_order_history.old_state</code>.
     */
    public void setOldState(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>matshop.shop_order_history.old_state</code>.
     */
    public String getOldState() {
        return (String) get(2);
    }

    /**
     * Setter for <code>matshop.shop_order_history.old_service_comment</code>.
     */
    public void setOldServiceComment(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>matshop.shop_order_history.old_service_comment</code>.
     */
    public String getOldServiceComment() {
        return (String) get(3);
    }

    /**
     * Setter for <code>matshop.shop_order_history.old_assigned_person_id</code>.
     */
    public void setOldAssignedPersonId(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>matshop.shop_order_history.old_assigned_person_id</code>.
     */
    public Long getOldAssignedPersonId() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>matshop.shop_order_history.new_state</code>.
     */
    public void setNewState(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>matshop.shop_order_history.new_state</code>.
     */
    public String getNewState() {
        return (String) get(5);
    }

    /**
     * Setter for <code>matshop.shop_order_history.new_service_comment</code>.
     */
    public void setNewServiceComment(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>matshop.shop_order_history.new_service_comment</code>.
     */
    public String getNewServiceComment() {
        return (String) get(6);
    }

    /**
     * Setter for <code>matshop.shop_order_history.new_assigned_person_id</code>.
     */
    public void setNewAssignedPersonId(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>matshop.shop_order_history.new_assigned_person_id</code>.
     */
    public Long getNewAssignedPersonId() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>matshop.shop_order_history.event_date</code>.
     */
    public void setEventDate(Date value) {
        set(8, value);
    }

    /**
     * Getter for <code>matshop.shop_order_history.event_date</code>.
     */
    public Date getEventDate() {
        return (Date) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Long, Long, String, String, Long, String, String, Long, Date> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Long, Long, String, String, Long, String, String, Long, Date> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return ShopOrderHistoryTable.SHOP_ORDER_HISTORY.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return ShopOrderHistoryTable.SHOP_ORDER_HISTORY.SHOP_ORDER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return ShopOrderHistoryTable.SHOP_ORDER_HISTORY.OLD_STATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return ShopOrderHistoryTable.SHOP_ORDER_HISTORY.OLD_SERVICE_COMMENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field5() {
        return ShopOrderHistoryTable.SHOP_ORDER_HISTORY.OLD_ASSIGNED_PERSON_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return ShopOrderHistoryTable.SHOP_ORDER_HISTORY.NEW_STATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return ShopOrderHistoryTable.SHOP_ORDER_HISTORY.NEW_SERVICE_COMMENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field8() {
        return ShopOrderHistoryTable.SHOP_ORDER_HISTORY.NEW_ASSIGNED_PERSON_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field9() {
        return ShopOrderHistoryTable.SHOP_ORDER_HISTORY.EVENT_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getShopOrderId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getOldState();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getOldServiceComment();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component5() {
        return getOldAssignedPersonId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getNewState();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getNewServiceComment();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component8() {
        return getNewAssignedPersonId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date component9() {
        return getEventDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getShopOrderId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getOldState();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getOldServiceComment();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value5() {
        return getOldAssignedPersonId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getNewState();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getNewServiceComment();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value8() {
        return getNewAssignedPersonId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value9() {
        return getEventDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ShopOrderHistoryRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ShopOrderHistoryRecord value2(Long value) {
        setShopOrderId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ShopOrderHistoryRecord value3(String value) {
        setOldState(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ShopOrderHistoryRecord value4(String value) {
        setOldServiceComment(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ShopOrderHistoryRecord value5(Long value) {
        setOldAssignedPersonId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ShopOrderHistoryRecord value6(String value) {
        setNewState(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ShopOrderHistoryRecord value7(String value) {
        setNewServiceComment(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ShopOrderHistoryRecord value8(Long value) {
        setNewAssignedPersonId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ShopOrderHistoryRecord value9(Date value) {
        setEventDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ShopOrderHistoryRecord values(Long value1, Long value2, String value3, String value4, Long value5, String value6, String value7, Long value8, Date value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ShopOrderHistoryRecord
     */
    public ShopOrderHistoryRecord() {
        super(ShopOrderHistoryTable.SHOP_ORDER_HISTORY);
    }

    /**
     * Create a detached, initialised ShopOrderHistoryRecord
     */
    public ShopOrderHistoryRecord(Long id, Long shopOrderId, String oldState, String oldServiceComment, Long oldAssignedPersonId, String newState, String newServiceComment, Long newAssignedPersonId, Date eventDate) {
        super(ShopOrderHistoryTable.SHOP_ORDER_HISTORY);

        set(0, id);
        set(1, shopOrderId);
        set(2, oldState);
        set(3, oldServiceComment);
        set(4, oldAssignedPersonId);
        set(5, newState);
        set(6, newServiceComment);
        set(7, newAssignedPersonId);
        set(8, eventDate);
    }
}
