/*
 * This file is generated by jOOQ.
 */
package ru.rich.matshop.db.model.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;

import ru.rich.matshop.db.model.tables.ShopOrderGoodsTable;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ShopOrderGoodsRecord extends UpdatableRecordImpl<ShopOrderGoodsRecord> implements Record5<Long, Long, Long, Integer, Long> {

    private static final long serialVersionUID = 1861849117;

    /**
     * Setter for <code>matshop.shop_order_goods.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>matshop.shop_order_goods.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>matshop.shop_order_goods.shop_order_id</code>.
     */
    public void setShopOrderId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>matshop.shop_order_goods.shop_order_id</code>.
     */
    public Long getShopOrderId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>matshop.shop_order_goods.product_id</code>.
     */
    public void setProductId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>matshop.shop_order_goods.product_id</code>.
     */
    public Long getProductId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>matshop.shop_order_goods.quantity</code>.
     */
    public void setQuantity(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>matshop.shop_order_goods.quantity</code>.
     */
    public Integer getQuantity() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>matshop.shop_order_goods.price</code>.
     */
    public void setPrice(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>matshop.shop_order_goods.price</code>.
     */
    public Long getPrice() {
        return (Long) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Long, Long, Long, Integer, Long> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Long, Long, Long, Integer, Long> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return ShopOrderGoodsTable.SHOP_ORDER_GOODS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return ShopOrderGoodsTable.SHOP_ORDER_GOODS.SHOP_ORDER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return ShopOrderGoodsTable.SHOP_ORDER_GOODS.PRODUCT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return ShopOrderGoodsTable.SHOP_ORDER_GOODS.QUANTITY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field5() {
        return ShopOrderGoodsTable.SHOP_ORDER_GOODS.PRICE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getShopOrderId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component3() {
        return getProductId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getQuantity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component5() {
        return getPrice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getShopOrderId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getProductId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getQuantity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value5() {
        return getPrice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ShopOrderGoodsRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ShopOrderGoodsRecord value2(Long value) {
        setShopOrderId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ShopOrderGoodsRecord value3(Long value) {
        setProductId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ShopOrderGoodsRecord value4(Integer value) {
        setQuantity(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ShopOrderGoodsRecord value5(Long value) {
        setPrice(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ShopOrderGoodsRecord values(Long value1, Long value2, Long value3, Integer value4, Long value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ShopOrderGoodsRecord
     */
    public ShopOrderGoodsRecord() {
        super(ShopOrderGoodsTable.SHOP_ORDER_GOODS);
    }

    /**
     * Create a detached, initialised ShopOrderGoodsRecord
     */
    public ShopOrderGoodsRecord(Long id, Long shopOrderId, Long productId, Integer quantity, Long price) {
        super(ShopOrderGoodsTable.SHOP_ORDER_GOODS);

        set(0, id);
        set(1, shopOrderId);
        set(2, productId);
        set(3, quantity);
        set(4, price);
    }
}
