/*
 * This file is generated by jOOQ.
 */
package ru.rich.matshop.db.model;


import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;

import ru.rich.matshop.db.model.tables.Address;
import ru.rich.matshop.db.model.tables.FlywaySchemaHistory;
import ru.rich.matshop.db.model.tables.Person;
import ru.rich.matshop.db.model.tables.Product;
import ru.rich.matshop.db.model.tables.ProductCosmetic;
import ru.rich.matshop.db.model.tables.ShopOrder;
import ru.rich.matshop.db.model.tables.ShopOrderGoods;
import ru.rich.matshop.db.model.tables.ShopOrderHistory;
import ru.rich.matshop.db.model.tables.Task;
import ru.rich.matshop.db.model.tables.TechLog;
import ru.rich.matshop.db.model.tables.records.AddressRecord;
import ru.rich.matshop.db.model.tables.records.FlywaySchemaHistoryRecord;
import ru.rich.matshop.db.model.tables.records.PersonRecord;
import ru.rich.matshop.db.model.tables.records.ProductCosmeticRecord;
import ru.rich.matshop.db.model.tables.records.ProductRecord;
import ru.rich.matshop.db.model.tables.records.ShopOrderGoodsRecord;
import ru.rich.matshop.db.model.tables.records.ShopOrderHistoryRecord;
import ru.rich.matshop.db.model.tables.records.ShopOrderRecord;
import ru.rich.matshop.db.model.tables.records.TaskRecord;
import ru.rich.matshop.db.model.tables.records.TechLogRecord;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>matshop</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<AddressRecord, Integer> IDENTITY_ADDRESS = Identities0.IDENTITY_ADDRESS;
    public static final Identity<PersonRecord, Integer> IDENTITY_PERSON = Identities0.IDENTITY_PERSON;
    public static final Identity<ProductRecord, Integer> IDENTITY_PRODUCT = Identities0.IDENTITY_PRODUCT;
    public static final Identity<ShopOrderRecord, Integer> IDENTITY_SHOP_ORDER = Identities0.IDENTITY_SHOP_ORDER;
    public static final Identity<ShopOrderGoodsRecord, Integer> IDENTITY_SHOP_ORDER_GOODS = Identities0.IDENTITY_SHOP_ORDER_GOODS;
    public static final Identity<ShopOrderHistoryRecord, Integer> IDENTITY_SHOP_ORDER_HISTORY = Identities0.IDENTITY_SHOP_ORDER_HISTORY;
    public static final Identity<TaskRecord, Integer> IDENTITY_TASK = Identities0.IDENTITY_TASK;
    public static final Identity<TechLogRecord, Integer> IDENTITY_TECH_LOG = Identities0.IDENTITY_TECH_LOG;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AddressRecord> ADDRESS_PKEY = UniqueKeys0.ADDRESS_PKEY;
    public static final UniqueKey<FlywaySchemaHistoryRecord> FLYWAY_SCHEMA_HISTORY_PK = UniqueKeys0.FLYWAY_SCHEMA_HISTORY_PK;
    public static final UniqueKey<PersonRecord> PERSON_PKEY = UniqueKeys0.PERSON_PKEY;
    public static final UniqueKey<ProductRecord> PRODUCT_PKEY = UniqueKeys0.PRODUCT_PKEY;
    public static final UniqueKey<ProductCosmeticRecord> PRODUCT_COSMETIC_PKEY = UniqueKeys0.PRODUCT_COSMETIC_PKEY;
    public static final UniqueKey<ShopOrderRecord> SHOP_ORDER_PKEY = UniqueKeys0.SHOP_ORDER_PKEY;
    public static final UniqueKey<ShopOrderGoodsRecord> SHOP_ORDER_GOODS_PKEY = UniqueKeys0.SHOP_ORDER_GOODS_PKEY;
    public static final UniqueKey<ShopOrderHistoryRecord> SHOP_ORDER_HISTORY_PKEY = UniqueKeys0.SHOP_ORDER_HISTORY_PKEY;
    public static final UniqueKey<TaskRecord> TASK_PKEY = UniqueKeys0.TASK_PKEY;
    public static final UniqueKey<TechLogRecord> TECH_LOG_PKEY = UniqueKeys0.TECH_LOG_PKEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<AddressRecord, Integer> IDENTITY_ADDRESS = Internal.createIdentity(Address.ADDRESS, Address.ADDRESS.ID);
        public static Identity<PersonRecord, Integer> IDENTITY_PERSON = Internal.createIdentity(Person.PERSON, Person.PERSON.ID);
        public static Identity<ProductRecord, Integer> IDENTITY_PRODUCT = Internal.createIdentity(Product.PRODUCT, Product.PRODUCT.ID);
        public static Identity<ShopOrderRecord, Integer> IDENTITY_SHOP_ORDER = Internal.createIdentity(ShopOrder.SHOP_ORDER, ShopOrder.SHOP_ORDER.ID);
        public static Identity<ShopOrderGoodsRecord, Integer> IDENTITY_SHOP_ORDER_GOODS = Internal.createIdentity(ShopOrderGoods.SHOP_ORDER_GOODS, ShopOrderGoods.SHOP_ORDER_GOODS.ID);
        public static Identity<ShopOrderHistoryRecord, Integer> IDENTITY_SHOP_ORDER_HISTORY = Internal.createIdentity(ShopOrderHistory.SHOP_ORDER_HISTORY, ShopOrderHistory.SHOP_ORDER_HISTORY.ID);
        public static Identity<TaskRecord, Integer> IDENTITY_TASK = Internal.createIdentity(Task.TASK, Task.TASK.ID);
        public static Identity<TechLogRecord, Integer> IDENTITY_TECH_LOG = Internal.createIdentity(TechLog.TECH_LOG, TechLog.TECH_LOG.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<AddressRecord> ADDRESS_PKEY = Internal.createUniqueKey(Address.ADDRESS, "address_pkey", Address.ADDRESS.ID);
        public static final UniqueKey<FlywaySchemaHistoryRecord> FLYWAY_SCHEMA_HISTORY_PK = Internal.createUniqueKey(FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, "flyway_schema_history_pk", FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.INSTALLED_RANK);
        public static final UniqueKey<PersonRecord> PERSON_PKEY = Internal.createUniqueKey(Person.PERSON, "person_pkey", Person.PERSON.ID);
        public static final UniqueKey<ProductRecord> PRODUCT_PKEY = Internal.createUniqueKey(Product.PRODUCT, "product_pkey", Product.PRODUCT.ID);
        public static final UniqueKey<ProductCosmeticRecord> PRODUCT_COSMETIC_PKEY = Internal.createUniqueKey(ProductCosmetic.PRODUCT_COSMETIC, "product_cosmetic_pkey", ProductCosmetic.PRODUCT_COSMETIC.PRODUCT_ID);
        public static final UniqueKey<ShopOrderRecord> SHOP_ORDER_PKEY = Internal.createUniqueKey(ShopOrder.SHOP_ORDER, "shop_order_pkey", ShopOrder.SHOP_ORDER.ID);
        public static final UniqueKey<ShopOrderGoodsRecord> SHOP_ORDER_GOODS_PKEY = Internal.createUniqueKey(ShopOrderGoods.SHOP_ORDER_GOODS, "shop_order_goods_pkey", ShopOrderGoods.SHOP_ORDER_GOODS.ID);
        public static final UniqueKey<ShopOrderHistoryRecord> SHOP_ORDER_HISTORY_PKEY = Internal.createUniqueKey(ShopOrderHistory.SHOP_ORDER_HISTORY, "shop_order_history_pkey", ShopOrderHistory.SHOP_ORDER_HISTORY.ID);
        public static final UniqueKey<TaskRecord> TASK_PKEY = Internal.createUniqueKey(Task.TASK, "task_pkey", Task.TASK.ID);
        public static final UniqueKey<TechLogRecord> TECH_LOG_PKEY = Internal.createUniqueKey(TechLog.TECH_LOG, "tech_log_pkey", TechLog.TECH_LOG.ID);
    }
}
