/*
 * This file is generated by jOOQ.
 */
package ru.rich.matshop.db.model;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import ru.rich.matshop.db.model.tables.AddressTable;
import ru.rich.matshop.db.model.tables.PersonTable;
import ru.rich.matshop.db.model.tables.ProductCosmeticTable;
import ru.rich.matshop.db.model.tables.ProductTable;
import ru.rich.matshop.db.model.tables.ShopOrderGoodsTable;
import ru.rich.matshop.db.model.tables.ShopOrderHistoryTable;
import ru.rich.matshop.db.model.tables.ShopOrderTable;
import ru.rich.matshop.db.model.tables.TaskTable;
import ru.rich.matshop.db.model.tables.TechLogTable;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Matshop extends SchemaImpl {

    private static final long serialVersionUID = -1546052032;

    /**
     * The reference instance of <code>matshop</code>
     */
    public static final Matshop MATSHOP = new Matshop();

    /**
     * The table <code>matshop.address</code>.
     */
    public final AddressTable ADDRESS = ru.rich.matshop.db.model.tables.AddressTable.ADDRESS;

    /**
     * The table <code>matshop.person</code>.
     */
    public final PersonTable PERSON = ru.rich.matshop.db.model.tables.PersonTable.PERSON;

    /**
     * The table <code>matshop.product</code>.
     */
    public final ProductTable PRODUCT = ru.rich.matshop.db.model.tables.ProductTable.PRODUCT;

    /**
     * The table <code>matshop.product_cosmetic</code>.
     */
    public final ProductCosmeticTable PRODUCT_COSMETIC = ru.rich.matshop.db.model.tables.ProductCosmeticTable.PRODUCT_COSMETIC;

    /**
     * The table <code>matshop.shop_order</code>.
     */
    public final ShopOrderTable SHOP_ORDER = ru.rich.matshop.db.model.tables.ShopOrderTable.SHOP_ORDER;

    /**
     * The table <code>matshop.shop_order_goods</code>.
     */
    public final ShopOrderGoodsTable SHOP_ORDER_GOODS = ru.rich.matshop.db.model.tables.ShopOrderGoodsTable.SHOP_ORDER_GOODS;

    /**
     * The table <code>matshop.shop_order_history</code>.
     */
    public final ShopOrderHistoryTable SHOP_ORDER_HISTORY = ru.rich.matshop.db.model.tables.ShopOrderHistoryTable.SHOP_ORDER_HISTORY;

    /**
     * The table <code>matshop.task</code>.
     */
    public final TaskTable TASK = ru.rich.matshop.db.model.tables.TaskTable.TASK;

    /**
     * The table <code>matshop.tech_log</code>.
     */
    public final TechLogTable TECH_LOG = ru.rich.matshop.db.model.tables.TechLogTable.TECH_LOG;

    /**
     * No further instances allowed
     */
    private Matshop() {
        super("matshop", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        List result = new ArrayList();
        result.addAll(getSequences0());
        return result;
    }

    private final List<Sequence<?>> getSequences0() {
        return Arrays.<Sequence<?>>asList(
            Sequences.ADDRESS_ID_SEQ,
            Sequences.PERSON_ID_SEQ,
            Sequences.PRODUCT_ID_SEQ,
            Sequences.SHOP_ORDER_GOODS_ID_SEQ,
            Sequences.SHOP_ORDER_HISTORY_ID_SEQ,
            Sequences.SHOP_ORDER_ID_SEQ,
            Sequences.TASK_ID_SEQ,
            Sequences.TECH_LOG_ID_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            AddressTable.ADDRESS,
            PersonTable.PERSON,
            ProductTable.PRODUCT,
            ProductCosmeticTable.PRODUCT_COSMETIC,
            ShopOrderTable.SHOP_ORDER,
            ShopOrderGoodsTable.SHOP_ORDER_GOODS,
            ShopOrderHistoryTable.SHOP_ORDER_HISTORY,
            TaskTable.TASK,
            TechLogTable.TECH_LOG);
    }
}
