/*
 * This file is generated by jOOQ.
 */
package ru.rich.matshop.db.model;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import ru.rich.matshop.db.model.tables.Address;
import ru.rich.matshop.db.model.tables.Person;
import ru.rich.matshop.db.model.tables.Product;
import ru.rich.matshop.db.model.tables.ProductCosmetic;
import ru.rich.matshop.db.model.tables.ShopOrder;
import ru.rich.matshop.db.model.tables.ShopOrderGoods;
import ru.rich.matshop.db.model.tables.ShopOrderHistory;
import ru.rich.matshop.db.model.tables.Task;
import ru.rich.matshop.db.model.tables.TechLog;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Matshop extends SchemaImpl {

    private static final long serialVersionUID = 589318944;

    /**
     * The reference instance of <code>matshop</code>
     */
    public static final Matshop MATSHOP = new Matshop();

    /**
     * The table <code>matshop.address</code>.
     */
    public final Address ADDRESS = ru.rich.matshop.db.model.tables.Address.ADDRESS;

    /**
     * The table <code>matshop.person</code>.
     */
    public final Person PERSON = ru.rich.matshop.db.model.tables.Person.PERSON;

    /**
     * The table <code>matshop.product</code>.
     */
    public final Product PRODUCT = ru.rich.matshop.db.model.tables.Product.PRODUCT;

    /**
     * The table <code>matshop.product_cosmetic</code>.
     */
    public final ProductCosmetic PRODUCT_COSMETIC = ru.rich.matshop.db.model.tables.ProductCosmetic.PRODUCT_COSMETIC;

    /**
     * The table <code>matshop.shop_order</code>.
     */
    public final ShopOrder SHOP_ORDER = ru.rich.matshop.db.model.tables.ShopOrder.SHOP_ORDER;

    /**
     * The table <code>matshop.shop_order_goods</code>.
     */
    public final ShopOrderGoods SHOP_ORDER_GOODS = ru.rich.matshop.db.model.tables.ShopOrderGoods.SHOP_ORDER_GOODS;

    /**
     * The table <code>matshop.shop_order_history</code>.
     */
    public final ShopOrderHistory SHOP_ORDER_HISTORY = ru.rich.matshop.db.model.tables.ShopOrderHistory.SHOP_ORDER_HISTORY;

    /**
     * The table <code>matshop.task</code>.
     */
    public final Task TASK = ru.rich.matshop.db.model.tables.Task.TASK;

    /**
     * The table <code>matshop.tech_log</code>.
     */
    public final TechLog TECH_LOG = ru.rich.matshop.db.model.tables.TechLog.TECH_LOG;

    /**
     * No further instances allowed
     */
    private Matshop() {
        super("matshop", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        List result = new ArrayList();
        result.addAll(getSequences0());
        return result;
    }

    private final List<Sequence<?>> getSequences0() {
        return Arrays.<Sequence<?>>asList(
            Sequences.ADDRESS_ID_SEQ,
            Sequences.PERSON_ID_SEQ,
            Sequences.PRODUCT_ID_SEQ,
            Sequences.SHOP_ORDER_GOODS_ID_SEQ,
            Sequences.SHOP_ORDER_HISTORY_ID_SEQ,
            Sequences.SHOP_ORDER_ID_SEQ,
            Sequences.TASK_ID_SEQ,
            Sequences.TECH_LOG_ID_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Address.ADDRESS,
            Person.PERSON,
            Product.PRODUCT,
            ProductCosmetic.PRODUCT_COSMETIC,
            ShopOrder.SHOP_ORDER,
            ShopOrderGoods.SHOP_ORDER_GOODS,
            ShopOrderHistory.SHOP_ORDER_HISTORY,
            Task.TASK,
            TechLog.TECH_LOG);
    }
}
