/*
 * This file is generated by jOOQ.
 */
package ru.rich.matshop.db.model;


import javax.annotation.Generated;

import ru.rich.matshop.db.model.tables.PCosmeticTable;
import ru.rich.matshop.db.model.tables.PTestTable;
import ru.rich.matshop.db.model.tables.PersonAddressTable;
import ru.rich.matshop.db.model.tables.PersonTable;
import ru.rich.matshop.db.model.tables.ProductFeatureTable;
import ru.rich.matshop.db.model.tables.ProductPricingTable;
import ru.rich.matshop.db.model.tables.ProductTable;
import ru.rich.matshop.db.model.tables.ShopOrderGoodsTable;
import ru.rich.matshop.db.model.tables.ShopOrderHistoryTable;
import ru.rich.matshop.db.model.tables.ShopOrderTable;
import ru.rich.matshop.db.model.tables.TaskTable;
import ru.rich.matshop.db.model.tables.TechLogTable;


/**
 * Convenience access to all tables in matshop
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>matshop.p_cosmetic</code>.
     */
    public static final PCosmeticTable P_COSMETIC = ru.rich.matshop.db.model.tables.PCosmeticTable.P_COSMETIC;

    /**
     * The table <code>matshop.p_test</code>.
     */
    public static final PTestTable P_TEST = ru.rich.matshop.db.model.tables.PTestTable.P_TEST;

    /**
     * The table <code>matshop.person</code>.
     */
    public static final PersonTable PERSON = ru.rich.matshop.db.model.tables.PersonTable.PERSON;

    /**
     * The table <code>matshop.person_address</code>.
     */
    public static final PersonAddressTable PERSON_ADDRESS = ru.rich.matshop.db.model.tables.PersonAddressTable.PERSON_ADDRESS;

    /**
     * The table <code>matshop.product</code>.
     */
    public static final ProductTable PRODUCT = ru.rich.matshop.db.model.tables.ProductTable.PRODUCT;

    /**
     * The table <code>matshop.product_feature</code>.
     */
    public static final ProductFeatureTable PRODUCT_FEATURE = ru.rich.matshop.db.model.tables.ProductFeatureTable.PRODUCT_FEATURE;

    /**
     * The table <code>matshop.product_pricing</code>.
     */
    public static final ProductPricingTable PRODUCT_PRICING = ru.rich.matshop.db.model.tables.ProductPricingTable.PRODUCT_PRICING;

    /**
     * The table <code>matshop.shop_order</code>.
     */
    public static final ShopOrderTable SHOP_ORDER = ru.rich.matshop.db.model.tables.ShopOrderTable.SHOP_ORDER;

    /**
     * The table <code>matshop.shop_order_goods</code>.
     */
    public static final ShopOrderGoodsTable SHOP_ORDER_GOODS = ru.rich.matshop.db.model.tables.ShopOrderGoodsTable.SHOP_ORDER_GOODS;

    /**
     * The table <code>matshop.shop_order_history</code>.
     */
    public static final ShopOrderHistoryTable SHOP_ORDER_HISTORY = ru.rich.matshop.db.model.tables.ShopOrderHistoryTable.SHOP_ORDER_HISTORY;

    /**
     * The table <code>matshop.task</code>.
     */
    public static final TaskTable TASK = ru.rich.matshop.db.model.tables.TaskTable.TASK;

    /**
     * The table <code>matshop.tech_log</code>.
     */
    public static final TechLogTable TECH_LOG = ru.rich.matshop.db.model.tables.TechLogTable.TECH_LOG;
}
