/*
 * This file is generated by jOOQ.
 */
package ru.rich.matshop.db.model.tables;


import java.util.Arrays;
import java.util.Date;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import ru.rich.matshop.db.converters.TimestampConverter;
import ru.rich.matshop.db.model.Indexes;
import ru.rich.matshop.db.model.Keys;
import ru.rich.matshop.db.model.Matshop;
import ru.rich.matshop.db.model.tables.records.PersonAddressRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PersonAddressTable extends TableImpl<PersonAddressRecord> {

    private static final long serialVersionUID = -819092086;

    /**
     * The reference instance of <code>matshop.person_address</code>
     */
    public static final PersonAddressTable PERSON_ADDRESS = new PersonAddressTable();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PersonAddressRecord> getRecordType() {
        return PersonAddressRecord.class;
    }

    /**
     * The column <code>matshop.person_address.id</code>.
     */
    public final TableField<PersonAddressRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('person_address_id_seq'::regclass)", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>matshop.person_address.person_id</code>.
     */
    public final TableField<PersonAddressRecord, Long> PERSON_ID = createField("person_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>matshop.person_address.region</code>.
     */
    public final TableField<PersonAddressRecord, String> REGION = createField("region", org.jooq.impl.SQLDataType.VARCHAR(200).nullable(false), this, "");

    /**
     * The column <code>matshop.person_address.town</code>.
     */
    public final TableField<PersonAddressRecord, String> TOWN = createField("town", org.jooq.impl.SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>matshop.person_address.street</code>.
     */
    public final TableField<PersonAddressRecord, String> STREET = createField("street", org.jooq.impl.SQLDataType.VARCHAR(200).nullable(false), this, "");

    /**
     * The column <code>matshop.person_address.house</code>.
     */
    public final TableField<PersonAddressRecord, String> HOUSE = createField("house", org.jooq.impl.SQLDataType.VARCHAR(10).nullable(false), this, "");

    /**
     * The column <code>matshop.person_address.housing</code>.
     */
    public final TableField<PersonAddressRecord, String> HOUSING = createField("housing", org.jooq.impl.SQLDataType.VARCHAR(10), this, "");

    /**
     * The column <code>matshop.person_address.construction</code>.
     */
    public final TableField<PersonAddressRecord, String> CONSTRUCTION = createField("construction", org.jooq.impl.SQLDataType.VARCHAR(10), this, "");

    /**
     * The column <code>matshop.person_address.apartment</code>.
     */
    public final TableField<PersonAddressRecord, String> APARTMENT = createField("apartment", org.jooq.impl.SQLDataType.VARCHAR(10), this, "");

    /**
     * The column <code>matshop.person_address.entrance</code>.
     */
    public final TableField<PersonAddressRecord, String> ENTRANCE = createField("entrance", org.jooq.impl.SQLDataType.VARCHAR(10), this, "");

    /**
     * The column <code>matshop.person_address.intercom</code>.
     */
    public final TableField<PersonAddressRecord, String> INTERCOM = createField("intercom", org.jooq.impl.SQLDataType.VARCHAR(10), this, "");

    /**
     * The column <code>matshop.person_address.address_comment</code>.
     */
    public final TableField<PersonAddressRecord, String> ADDRESS_COMMENT = createField("address_comment", org.jooq.impl.SQLDataType.VARCHAR(1000), this, "");

    /**
     * The column <code>matshop.person_address.edit_date</code>.
     */
    public final TableField<PersonAddressRecord, Date> EDIT_DATE = createField("edit_date", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "", new TimestampConverter());

    /**
     * Create a <code>matshop.person_address</code> table reference
     */
    public PersonAddressTable() {
        this(DSL.name("person_address"), null);
    }

    /**
     * Create an aliased <code>matshop.person_address</code> table reference
     */
    public PersonAddressTable(String alias) {
        this(DSL.name(alias), PERSON_ADDRESS);
    }

    /**
     * Create an aliased <code>matshop.person_address</code> table reference
     */
    public PersonAddressTable(Name alias) {
        this(alias, PERSON_ADDRESS);
    }

    private PersonAddressTable(Name alias, Table<PersonAddressRecord> aliased) {
        this(alias, aliased, null);
    }

    private PersonAddressTable(Name alias, Table<PersonAddressRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> PersonAddressTable(Table<O> child, ForeignKey<O, PersonAddressRecord> key) {
        super(child, key, PERSON_ADDRESS);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Matshop.MATSHOP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.IDX_PAD_PERSON_ID, Indexes.PERSON_ADDRESS_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<PersonAddressRecord, Long> getIdentity() {
        return Keys.IDENTITY_PERSON_ADDRESS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<PersonAddressRecord> getPrimaryKey() {
        return Keys.PERSON_ADDRESS_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<PersonAddressRecord>> getKeys() {
        return Arrays.<UniqueKey<PersonAddressRecord>>asList(Keys.PERSON_ADDRESS_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<PersonAddressRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<PersonAddressRecord, ?>>asList(Keys.PERSON_ADDRESS__PERSON_ADDRESS_PERSON_ID_FKEY);
    }

    public PersonTable person() {
        return new PersonTable(this, Keys.PERSON_ADDRESS__PERSON_ADDRESS_PERSON_ID_FKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PersonAddressTable as(String alias) {
        return new PersonAddressTable(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PersonAddressTable as(Name alias) {
        return new PersonAddressTable(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public PersonAddressTable rename(String name) {
        return new PersonAddressTable(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PersonAddressTable rename(Name name) {
        return new PersonAddressTable(name, null);
    }
}
