/*
 * This file is generated by jOOQ.
 */
package ru.rich.matshop.db.model.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import ru.rich.matshop.db.model.Indexes;
import ru.rich.matshop.db.model.Keys;
import ru.rich.matshop.db.model.Matshop;
import ru.rich.matshop.db.model.tables.records.ShopOrderHistoryRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ShopOrderHistoryTable extends TableImpl<ShopOrderHistoryRecord> {

    private static final long serialVersionUID = 1551392075;

    /**
     * The reference instance of <code>matshop.shop_order_history</code>
     */
    public static final ShopOrderHistoryTable SHOP_ORDER_HISTORY = new ShopOrderHistoryTable();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ShopOrderHistoryRecord> getRecordType() {
        return ShopOrderHistoryRecord.class;
    }

    /**
     * The column <code>matshop.shop_order_history.id</code>.
     */
    public final TableField<ShopOrderHistoryRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('shop_order_history_id_seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>matshop.shop_order_history.shop_order_id</code>.
     */
    public final TableField<ShopOrderHistoryRecord, Integer> SHOP_ORDER_ID = createField("shop_order_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>matshop.shop_order_history.old_state</code>.
     */
    public final TableField<ShopOrderHistoryRecord, String> OLD_STATE = createField("old_state", org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>matshop.shop_order_history.old_service_comment</code>.
     */
    public final TableField<ShopOrderHistoryRecord, String> OLD_SERVICE_COMMENT = createField("old_service_comment", org.jooq.impl.SQLDataType.VARCHAR(10000), this, "");

    /**
     * The column <code>matshop.shop_order_history.old_assigned_person_id</code>.
     */
    public final TableField<ShopOrderHistoryRecord, Integer> OLD_ASSIGNED_PERSON_ID = createField("old_assigned_person_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>matshop.shop_order_history.new_state</code>.
     */
    public final TableField<ShopOrderHistoryRecord, String> NEW_STATE = createField("new_state", org.jooq.impl.SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>matshop.shop_order_history.new_service_comment</code>.
     */
    public final TableField<ShopOrderHistoryRecord, String> NEW_SERVICE_COMMENT = createField("new_service_comment", org.jooq.impl.SQLDataType.VARCHAR(10000), this, "");

    /**
     * The column <code>matshop.shop_order_history.new_assigned_person_id</code>.
     */
    public final TableField<ShopOrderHistoryRecord, Integer> NEW_ASSIGNED_PERSON_ID = createField("new_assigned_person_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>matshop.shop_order_history.event_date</code>.
     */
    public final TableField<ShopOrderHistoryRecord, Timestamp> EVENT_DATE = createField("event_date", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * Create a <code>matshop.shop_order_history</code> table reference
     */
    public ShopOrderHistoryTable() {
        this(DSL.name("shop_order_history"), null);
    }

    /**
     * Create an aliased <code>matshop.shop_order_history</code> table reference
     */
    public ShopOrderHistoryTable(String alias) {
        this(DSL.name(alias), SHOP_ORDER_HISTORY);
    }

    /**
     * Create an aliased <code>matshop.shop_order_history</code> table reference
     */
    public ShopOrderHistoryTable(Name alias) {
        this(alias, SHOP_ORDER_HISTORY);
    }

    private ShopOrderHistoryTable(Name alias, Table<ShopOrderHistoryRecord> aliased) {
        this(alias, aliased, null);
    }

    private ShopOrderHistoryTable(Name alias, Table<ShopOrderHistoryRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> ShopOrderHistoryTable(Table<O> child, ForeignKey<O, ShopOrderHistoryRecord> key) {
        super(child, key, SHOP_ORDER_HISTORY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Matshop.MATSHOP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.IDX_SOH_NEW_A_PERSON_ID, Indexes.IDX_SOH_OLD_A_PERSON_ID, Indexes.IDX_SOH_SHOP_ORDER_ID, Indexes.SHOP_ORDER_HISTORY_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<ShopOrderHistoryRecord, Integer> getIdentity() {
        return Keys.IDENTITY_SHOP_ORDER_HISTORY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ShopOrderHistoryRecord> getPrimaryKey() {
        return Keys.SHOP_ORDER_HISTORY_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ShopOrderHistoryRecord>> getKeys() {
        return Arrays.<UniqueKey<ShopOrderHistoryRecord>>asList(Keys.SHOP_ORDER_HISTORY_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<ShopOrderHistoryRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<ShopOrderHistoryRecord, ?>>asList(Keys.SHOP_ORDER_HISTORY__SHOP_ORDER_HISTORY_SHOP_ORDER_ID_FKEY, Keys.SHOP_ORDER_HISTORY__SHOP_ORDER_HISTORY_OLD_ASSIGNED_PERSON_ID_FKEY, Keys.SHOP_ORDER_HISTORY__SHOP_ORDER_HISTORY_NEW_ASSIGNED_PERSON_ID_FKEY);
    }

    public ShopOrderTable shopOrder() {
        return new ShopOrderTable(this, Keys.SHOP_ORDER_HISTORY__SHOP_ORDER_HISTORY_SHOP_ORDER_ID_FKEY);
    }

    public PersonTable shopOrderHistory_ShopOrderHistoryOldAssignedPersonIdFkey() {
        return new PersonTable(this, Keys.SHOP_ORDER_HISTORY__SHOP_ORDER_HISTORY_OLD_ASSIGNED_PERSON_ID_FKEY);
    }

    public PersonTable shopOrderHistory_ShopOrderHistoryNewAssignedPersonIdFkey() {
        return new PersonTable(this, Keys.SHOP_ORDER_HISTORY__SHOP_ORDER_HISTORY_NEW_ASSIGNED_PERSON_ID_FKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ShopOrderHistoryTable as(String alias) {
        return new ShopOrderHistoryTable(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ShopOrderHistoryTable as(Name alias) {
        return new ShopOrderHistoryTable(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ShopOrderHistoryTable rename(String name) {
        return new ShopOrderHistoryTable(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ShopOrderHistoryTable rename(Name name) {
        return new ShopOrderHistoryTable(name, null);
    }
}
