CREATE TABLE TASK (
  ID        SERIAL PRIMARY KEY,
  NAME      VARCHAR(1000) NOT NULL,
  TYPE      VARCHAR(100) NOT NULL,
  STATE     VARCHAR(100) NOT NULL,
  LAST_DATA TIMESTAMP(3) NOT NULL,
  EDIT_DATE TIMESTAMP(3) NOT NULL
);

