CREATE TABLE SHOP_ORDER (
  ID         SERIAL PRIMARY KEY,
  SHOP_ID    INT          NOT NULL,
  PERSON_ID  INT          NOT NULL REFERENCES PERSON (ID),
  ADDRESS_ID INT REFERENCES ADDRESS (ID),
  AMMOUNT    BIGINT,
  STATE      VARCHAR(100) NOT NULL,
  EDIT_DATE  TIMESTAMP(3) NOT NULL
);

CREATE TABLE SHOP_ORDER_GOODS (
  ID            SERIAL PRIMARY KEY,
  SHOP_ORDER_ID INT NOT NULL REFERENCES SHOP_ORDER (ID),
  PRODUCT_ID    INT NOT NULL REFERENCES PRODUCT (ID),
  QUANTITY      INT,
  PRICE         BIGINT
);