CREATE TABLE PRODUCT (
  ID             BIGSERIAL PRIMARY KEY,
  SHOP_ID        INT           NOT NULL,
  NAME           VARCHAR(4000) NOT NULL,
  EDIT_DATE      TIMESTAMP(3)  NOT NULL,
  STATE          VARCHAR(100)  NOT NULL,
  DATA           TEXT          NOT NULL,
  BASE_PRICE     BIGINT,
  PRICING        VARCHAR(4000),
  FORMAT_VERSION VARCHAR(100)  NOT NULL
);

ALTER SEQUENCE PRODUCT_ID_SEQ
  INCREMENT BY 1033;

CREATE INDEX IDX_PRO_NAME
  ON PRODUCT (NAME);
CREATE INDEX IDX_PRO_EDIT_DATE
  ON PRODUCT (EDIT_DATE);

CREATE TABLE PRODUCT_PRICING (
  ID        BIGSERIAL PRIMARY KEY,
  SHOP_ID   INT           NOT NULL,
  PRICING   VARCHAR(4000) NOT NULL,
  EDIT_DATE TIMESTAMP(3)  NOT NULL
);

CREATE TABLE P_TEST (
  PRODUCT_ID BIGINT PRIMARY KEY REFERENCES PRODUCT (ID),
  PRICE      BIGINT NOT NULL,
  DISCOUNT   VARCHAR(100),
  POPULARITY BIGINT NOT NULL DEFAULT 0,
  BRAND      BIGINT NOT NULL
);

CREATE INDEX IDX_PTS_PRICE
  ON P_TEST (PRICE);
CREATE INDEX IDX_PTS_NAME
  ON P_TEST (DISCOUNT);
CREATE INDEX IDX_PTS_POPULARITY
  ON P_TEST (POPULARITY);
CREATE INDEX IDX_PTS_CATEGORY
  ON P_TEST (BRAND);

CREATE TABLE P_COSMETIC (
  PRODUCT_ID BIGINT PRIMARY KEY REFERENCES PRODUCT (ID),
  PRICE      BIGINT NOT NULL,
  DISCOUNT   VARCHAR(100),
  POPULARITY BIGINT NOT NULL DEFAULT 0,
  BRAND      VARCHAR(1000)
);

CREATE INDEX IDX_PCS_PRICE
  ON P_COSMETIC (PRICE);
CREATE INDEX IDX_PCS_NAME
  ON P_COSMETIC (DISCOUNT);
CREATE INDEX IDX_PCS_POPULARITY
  ON P_COSMETIC (POPULARITY);
CREATE INDEX IDX_PCS_CATEGORY
  ON P_COSMETIC (BRAND);

