CREATE TABLE PRODUCT (
  ID             SERIAL PRIMARY KEY,
  SHOP_ID        INT          NOT NULL,
  DATA           TEXT         NOT NULL,
  EDIT_DATE      TIMESTAMP(3) NOT NULL,
  STATE          VARCHAR(100) NOT NULL,
  FORMAT_VERSION VARCHAR(100) NOT NULL
);

CREATE TABLE PRODUCT_COSMETIC (
  PRODUCT_ID INT PRIMARY KEY REFERENCES PRODUCT (ID),
  NAME       VARCHAR(4000) NOT NULL,
  PRICE      BIGINT        NOT NULL,
  CATEGORY   INT           NOT NULL,
  POPULARITY BIGINT        NOT NULL DEFAULT 0
);