CREATE TABLE ORDER (
  ID         SERIAL PRIMARY KEY,
  SHOP_ID    INT          NOT NULL,
  PERSON_ID  INT          NOT NULL,
  ADDRESS_ID INT,
  AMMOUNT    BIGINT,
  STATE      VARCHAR(100) NOT NULL,
  EDIT_DATE  TIMESTAMP(3) NOT NULL
);

CREATE TABLE ORDER_GOODS (
  ID         SERIAL PRIMARY KEY,
  ORDER_ID   INT NOT NULL,
  PRODUCT_ID INT NOT NULL,
  QUANTITY   INT,
  PRICE      BIGINT
);